apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          
          
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: MYSQL_ROOT_PASSWORD            
            
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage

      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
